### ISSUE TITLE
AttributeError: module 'marathon' has no attribute 'MarathonClient'

### ISSUE THREAD

**Issue by rajivreddy** [thefactory/marathon-python#100]
Hi,

I installed package through pip

when i try to load **"from marathon import MarathonClient" **in script, i am getting an error message.
marathon.py file:

> import marathon
> 
> c = marathon.MarathonClient("http://10.10.201.71:8080")

Error:
Traceback (most recent call last):
  File "/Users/rajivreddy/PycharmProjects/Ezbuilder/source/marathon.py", line 1, in <module>
    import marathon
  File "/Users/rajivreddy/PycharmProjects/Ezbuilder/source/marathon.py", line 3, in <module>
    c = marathon.MarathonClient("http://10.10.201.71:8080")
AttributeError: module 'marathon' has no attribute 'MarathonClient'

Python Version:
$python --version
Python 3.5.1 :: Continuum Analytics, Inc.

**Comment by Rob-Johnson** [comment]
I suspect your marathon module is clashing with the one you're trying to import. Try renaming your ``marathon.py`` to ``foo.py`` and I suspect it'll work just fine.

**Comment by rajivreddy** [comment]
Yep,

Thank you
