### ISSUE TITLE
c.scale_app('myapp3', 2)

### ISSUE THREAD

**Issue by houht** [thefactory/marathon-python#102]
in README.md  example：

c.scale_app('myapp3', 2)

Maybe a total of 2, instead of 3？

**Comment by solarkennedy** [comment]
Can you tell me more or make a PR?

**Comment by houht** [comment]
>>> 
>>> from marathon import MarathonClient
>>> c = MarathonClient('http://10.0.2.47:8090')
>>> from marathon.models import MarathonApp
>>> c.create_app('myapp3', MarathonApp(cmd='sleep 100', mem=16, cpus=1))
MarathonApp::/myapp3
>>> c.get_app('myapp3').instances
1
>>> c.scale_app('myapp3', 2)
{u'deploymentId': u'8a213b34-97b6-40d0-bb93-ba18e9578bb0', u'version': u'2016-05-13T01:30:22.661Z'}
>>> c.get_app('myapp3').instances
2

########################################################

in your README.md example：

>>> c.get_app('myapp3').instances
1
>>> c.scale_app('myapp3', 2)
{'deploymentId': '611b89e3-99f2-4d8a-afe1-ec0b83fdbb88', 'version': '2014-08-26T07:40:20.121Z'}
>>> c.get_app('myapp3').instances
3


so in scale_app function may be the inside of the parameter should be the final number of instances

**Comment by solarkennedy** [comment]
Fixed. In the future feel free to simply open a PR directly with a fix.
