### ISSUE TITLE
Wrongly use version_info as task_stats

### ISSUE THREAD

**Issue by oilbeater** [thefactory/marathon-python#104]
In line https://github.com/thefactory/marathon-python/blob/master/marathon/models/app.py#L149 `version_info` is used as `task_stats` if no `task_stats` provided. However the newest version marathon api show that their format are different and they are also different in what `MarathonAppVersionInfo` and `MarathonTaskStats` defined in code. So this will cause load a json from `MarathonApp.to_json()` result failed, as the `task_stats` format in json and what `MarathonApp` need is different.

Also taskStats will not returned from marathon if `?embed=apps.taskStats` params is not specified and now the client has no way to specify this param, so the `task_stats` is always wrong.

I am not sure if there are some compatibility consideration to use version_info as task_stats. If not maybe  this part should be removed, and also need a new param like `embed_task_stats` in get_app.

**Comment by solarkennedy** [comment]
Do you know when this changed happen? If it was post 1.0 then I would say just remove it.

**Comment by oilbeater** [comment]
It seems like some copy paste error, I will check into this and make another PR later.
