### ISSUE TITLE
Supporting creating applications with a json file (or json-formatted string, or json object)

### ISSUE THREAD

**Issue by vincepii** [thefactory/marathon-python#112]
The `marathon.MarathonApp` object can be built by passing all the parameters defining an application.

It would be nice if there was a way to create `marathon.MarathonApp` with json content directly.

A workaround, given a json object, would be to use `marathon.MarathonApp(**myapp_json)`, but there would still be issues for method parameters using snake-case and json keys using camelCase:

E.g.,
```
TypeError: __init__() got an unexpected keyword argument 'upgradeStrategy'
```

**Comment by oilbeater** [comment]
Try MarathonApp.from_json()

**Comment by vincepii** [comment]
Thanks, for reference, the following works:
```
    c = marathon.MarathonClient(uri)
    app = marathon.MarathonApp.from_json(json.loads(json_definition))
    ret = c.create_app(appid, app)
```
