### ISSUE TITLE
[Question] Passing parameters to request.get 

### ISSUE THREAD

**Issue by migueleliasweb** [thefactory/marathon-python#132]
Here in the company where I work we can only access the marathon api through a proxy, but sadly I cannot pass any extra parameter to requests.session.

A simple workaround would be to implement an additional argument that could be passed on the class initialization with extra parameters, something like:

``` python
class MarathonClient(object):

    """Client interface for the Marathon REST API."""

    def __init__(self, servers, username=None, password=None, timeout=10, requests_extra_args={}):
        #some ommited code
        self.requests_extra_args = requests_extra_args

     def _do_request(self, method, path, params=None, data=None):
        """Query Marathon server."""
        headers = {
            'Content-Type': 'application/json',
            'Accept': 'application/json'
        }

        headers.update(self.requests_extra_args)
```

What do  you think ? Does this worth a PR ?

**Comment by solarkennedy** [comment]
Can you set `HTTP_PROXY` instead?
http://docs.python-requests.org/en/master/user/advanced/#proxies

**Comment by migueleliasweb** [comment]
That actually worked just fine !
