### ISSUE TITLE
HTTP 400 returned with message, "Invalid JSON"

### ISSUE THREAD

**Issue by EslamElHusseiny** [thefactory/marathon-python#133]
I'm trying to update a currently deployed app but it returns `400 returned with message, "Invalid JSON"`

code snippit 
```
client = MarathonClient(marathon_endpoints)
app = client.get_app(app_id)
client.update_app(app_id, app, force=True)
```
and the traceback : 
```
No handlers could be found for logger "marathon"
Traceback (most recent call last):
  File "/update_app.py", line 49, in <module>
    client.update_app(app_id, app, force=True)
  File "/usr/lib/python2.7/site-packages/marathon/client.py", line 252, in update_app
    app.version = None
  File "/usr/lib/python2.7/site-packages/marathon/client.py", line 85, in _do_request
    raise MarathonHttpError(response)
MarathonHttpError: MarathonHttpError: HTTP 400 returned with message, "Invalid JSON"
```
I'm using `marathon v0.15.3` and `python-marathon v0.8.4`
any ideas what's going wrong ?

**Comment by EslamElHusseiny** [comment]
I've found that the returning JSON includes both fetch and URIs which both can't exist in the same JSON. 

my workaround now is to empty one of them

**Comment by solarkennedy** [comment]
Glad you figured it out, any suggestions for how to improve? I guess we could validate in the model way early?

**Comment by EslamElHusseiny** [comment]
I think this is a Marathon specific issue, cause I used to do the same without any issues.

**Comment by solarkennedy** [comment]
Gotcha.
