### ISSUE TITLE
Unknown event_type app_terminated_event

### ISSUE THREAD

**Issue by krainz** [thefactory/marathon-python#151]
i used the event stream api, when the marathon responsed it sounds lose a event type class :

`File "/usr/lib/python3.4/site-packages/marathon/client.py", line 742, in event_stream
    yield ef.process(event_data)
  File "/usr/lib/python3.4/site-packages/marathon/models/events.py", line 156, in process
    raise MarathonError('Unknown event_type: {}, data: {}'.format(event_type, event))
marathon.exceptions.MarathonError: Unknown event_type: app_terminated_event, data: {'timestamp': '2016-10-08T11:43:40.843Z', 'appId': '/order-service-u103', 'eventType': 'app_terminated_event'}`

**Comment by solarkennedy** [comment]
It looks like we didn't have this event at the time. Can you make a PR?
https://github.com/thefactory/marathon-python/blob/75f23876f41d767216fb81bd562f148cd7bbb28a/marathon/models/events.py#L128

**Comment by Jbrownstone** [comment]
Hello,

I had the same problem, and i did the pr fixing the issue.
