### ISSUE TITLE
Travis tests have stopped automatically running

### ISSUE THREAD

**Issue by solarkennedy** [thefactory/marathon-python#194]
@mbabineau I opened a ticket with travisci, and they said ask github.

But first, can you try "turning it off and on again" with travisci in the repo settings? (I don't have access)

**Comment by mbabineau** [comment]
Handle successfully jiggled and tests successfully (re-)run:
https://travis-ci.org/thefactory/marathon-python/builds/218227859

**Comment by solarkennedy** [comment]
Hmm. Yea the trigger still is not triggering (see #195).

What are we missing......

**Comment by solarkennedy** [comment]
They seem to be running now.
