### ISSUE TITLE
Wrong health check object generated for COMMAND protocol

### ISSUE THREAD

**Issue by protetore** [thefactory/marathon-python#222]
The current version of marathon-python (0.9.2) generates `COMMAND` type protocol healthchecks *command* property as a string, but current version of marathon expects an object with the 'value' property:

**Current:**
```json
{
  "protocol": "COMMAND",
  "command":  "curl -f -X GET http://$HOST:$PORT0/health"
}
```

**Expected:**
```json
{
  "protocol": "COMMAND",
  "command": { "value": "curl -f -X GET http://$HOST:$PORT0/health" }
}
```

My workaround was to create the health check like this:
```python
healthchecks.append(MarathonHealthCheck(
    protocol=hc.protocol,
    command={"value": hc.cmd}
))
```

I can make a pull request to address this, but there are some questions:

1. This should be fixed or we should assume the we have to send the object in the correct format? (:-1:)
2. This should be fixed, but there must be a quick test to see if the received command is already an object to avoid breaking the code of those who are creating the like I am?
3. Just change the code to create the format expected by marathon and let people fix if they bump into some error?

**Comment by solarkennedy** [comment]
@protetore can you track down exactly when this behavior changed in Marathon?

**Comment by protetore** [comment]
I've checked in oldest tag I could find in Marathon repo (1.1.1) and it already required the nested value object.

Then I went to the oldest release branch (release/0.13) and it was already there too.

In their words: "command health checks WITHOUT a nested value should be rejected"

**Comment by solarkennedy** [comment]
Yea I guess at Yelp we've been passing in the value dictionary.

Please do your solution number 2 and print a deprecation error.
