### ISSUE TITLE
Urgent BUG: to_json() is returning unexpected result under python3 version

### ISSUE THREAD

**Issue by vitan** [thefactory/marathon-python#26]
In a nutshell, under python3 version, we should replace ``iteritems`` with ``items`` in file https://github.com/thefactory/marathon-python/blob/master/marathon/util.py. I saw that you forgot to change ``hasattr(obj, 'iteritems')`` to ``hasattr(obj, 'items')``.

**Comment by bacoboy** [comment]
Submit a pull request! :wink:

**Comment by vitan** [comment]
@bacoboy , I had a try yesterday, but I don't think I have understood the code well about how to identify python version. Just index me if possible and I will spend some time to read the code further. BTW, the following is the patch of https://github.com/thefactory/marathon-python/blob/master/marathon/util.py:

```patch
23c23
<             if hasattr(obj, 'iteritems'):
---
>             if hasattr(obj, 'items'):
42c42
<             if hasattr(obj, 'iteritems'):
---
>             if hasattr(obj, 'items'):
```

**Comment by vitan** [comment]
I found that there is different content in the file ``util.py`` between which downloaded by ``pip3 install marathon`` and by ``wget https://github.com/thefactory/marathon-python/archive/0.6.13.tar.gz``. How did you make it?

**Comment by mbabineau** [comment]
Nothing special, just
```console
$ python setup.py sdist upload
```
