### ISSUE TITLE
Downloading Log For App

### ISSUE THREAD

**Issue by Sn3akyP3t3** [thefactory/marathon-python#265]
This is likely not actually an issue, but more of a question.  I don't know if the API itself even supports this.  Does this library have the capability to pull a log for a specific app?  I was hoping to do this via the library and not some alternative way like Selenium.

**Comment by solarkennedy** [comment]
It does not.
The API isn't there, and probably will never be :(
Selenium sounds a tad heavy handed, maybe a more simple python html parser?

In the long run, we (this library) can only really support things that are in the api.
