### ISSUE TITLE
create_app() not working for docker container

### ISSUE THREAD

**Issue by arasananbu** [thefactory/marathon-python#28]
Hi, Below is the script i am trying to create a docker container using Marathon.
I doubt the issue with the json data sent in create_app()

from marathon import MarathonClient
from marathon.models import MarathonApp
from marathon.models.container import MarathonContainer
from marathon.models.container import MarathonDockerContainer

marathonApp = MarathonApp(cmd = 'while sleep 10; do date -u +%T; done', container = {'docker': {'image': 'ubuntu:latest', 'network': 'BRIDGE'}, 'type': 'DOCKER'}, cpus = 0.5, instances = 2, mem = 128)
marathonClient = MarathonClient('localhost:8082/')
marathonClient.create_app('/anbu/tst-ubuntu-ssh', marathonApp)

Getting error response as 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.2/site-packages/marathon/client.py", line 109, in create_app
    return self._parse_response(response, MarathonApp)
  File "/usr/lib/python3.2/site-packages/marathon/client.py", line 52, in _parse_response
    return clazz.from_json(target)
  File "/usr/lib/python3.2/site-packages/marathon/models/base.py", line 30, in from_json
    return cls(**{to_snake_case(k): v for k,v in attributes.items()})
  File "/usr/lib/python3.2/site-packages/marathon/models/app.py", line 88, in __init__
    else MarathonContainer.from_json(container)
  File "/usr/lib/python3.2/site-packages/marathon/models/base.py", line 30, in from_json
    return cls(**{to_snake_case(k): v for k,v in attributes.items()})
  File "/usr/lib/python3.2/site-packages/marathon/models/container.py", line 25, in __init__
    else MarathonDockerContainer().from_json(docker)
  File "/usr/lib/python3.2/site-packages/marathon/models/base.py", line 30, in from_json
    return cls(**{to_snake_case(k): v for k,v in attributes.items()})
AttributeError: 'NoneType' object has no attribute 'items'
>>>

Tried to dump the JSON sent in create_app().
{"cmd": "while sleep 10; do date -u +%T; done", "container": ["docker", "type"], "cpus": 0.5, "id": "/anbu/tst-ubuntu-ssh", "instances": 2, "mem": 128}

**Comment by mbabineau** [comment]
Using the latest release of marathon-python (`0.6.13`), I was able to deploy your app to a Marathon 0.8.1 server without any changes:
```python
>>> import marathon
>>> c = marathon.MarathonClient("http://marathon.example.net:8080")
>>> m = marathon.MarathonApp(cmd = 'while sleep 10; do date -u +%T; done', container = {'docker': {'image': 'ubuntu:latest', 'network': 'BRIDGE'}, 'type': 'DOCKER'}, cpus = 0.5, instances = 2, mem = 128)
>>> c.create_app('foo', m)
MarathonApp::/foo
```

Your JSON output seems to have a bad `container` field. You should see:
```python
>>> marathon.MarathonApp(cmd = 'while sleep 10; do date -u +%T; done', container = {'docker': {'image': 'ubuntu:latest', 'network': 'BRIDGE'}, 'type': 'DOCKER'}, cpus = 0.5, instances = 2, mem = 128).to_json()
'{"cmd": "while sleep 10; do date -u +%T; done", "container": {"docker": {"image": "ubuntu:latest", "network": "BRIDGE", "privileged": false}, "type": "DOCKER"}, "cpus": 0.5, "instances": 2, "mem": 128}'
```

What version are you using? Can you try reinstalling, perhaps in a [new] virtualenv?

**Comment by mbabineau** [comment]
I'm using Python 2.7.6, and it looks like you're using Python 3.2. I wonder if this is related to https://github.com/thefactory/marathon-python/pull/27.

Assuming you're using 0.6.13, would you mind installing from `master` instead?
```bash
pip install -e git+git@github.com:thefactory/marathon-python.git#egg=marathon
```

**Comment by arasananbu** [comment]
I am not able to load marathon module with python 2.7.8. I am using "marathon-0.6.13"

FYI, I am using cygwin.... Not sure, is this a problem.

Python 2.7.8 (default, Jul 28 2014, 01:34:03)
[GCC 4.8.3] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from marathon import MarathonClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/marathon-0.6.13-py2.7.egg/marathon/__init__.py", line 3, in <module>
    from .client import MarathonClient
  File "/usr/lib/python2.7/site-packages/marathon-0.6.13-py2.7.egg/marathon/client.py", line 14, in <module>
    import requests
ImportError: No module named requests

**Comment by mbabineau** [comment]
Not sure about how things work in cygwin, but installing from pip should get you all the (requirements)[https://github.com/thefactory/marathon-python/blob/master/setup.py#L14]. In any case, you just need to install the `requests` package ([this `requests`](http://docs.python-requests.org/en/latest/#))
```bash
pip install requests
```

**Comment by mbabineau** [comment]
That should have fixed it - please feel free to reopen if you're still having trouble with `requests`
