### ISSUE TITLE
Marathon app name validation is broken

### ISSUE THREAD

**Issue by keshavdv** [thefactory/marathon-python#45]
All app names seem to be considered invalid. The regular expression appears to be wrong

```
import re
ID_PATTERN = re.compile(r'^(?:(?:[a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*(?:[a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])$')
print ID_PATTERN.match('foo.bar') # None
```

**Comment by fengyehong** [comment]
+1
Meet the same problem.
I think we should remove the **r** operator before the regular expression string. 
It's double backslash in the string!

**Comment by solarkennedy** [comment]
Closed by #44 or whatever replaces it.

**Comment by solarkennedy** [comment]
I've merged in a fix from the Yelp fork.

@mbabineau can you do a new release to include these fixes?

**Comment by mbabineau** [comment]
Done with 13fe7c3e0f3f52af47bb1f9f1d0e3af4b5b1ca7b:
https://pypi.python.org/pypi/marathon/0.7.1
