### ISSUE TITLE
Why MarathonDockerContainer.parameters is defined as dict?

### ISSUE THREAD

**Issue by fengyehong** [thefactory/marathon-python#47]
I noticed that `parameters ` is defined as dict, but according to Marathon dockument https://mesosphere.github.io/marathon/docs/native-docker.html#privileged-mode-and-arbitrary-docker-options, it should be a list.

This leads to error when calling `create_app`, `update_app` with `minimal=False` even `parameters` is empty.

**Comment by solarkennedy** [comment]
This was part of the api change to 0.8.0:
https://github.com/mesosphere/marathon/releases/tag/v0.8.0

Can you confirm the version of marathon and the version of marathon-python you are using?

**Comment by fengyehong** [comment]
thanks, solarkennedy

I'am using marathon-python==0.6.13 and marathon 0.8.0

**Comment by solarkennedy** [comment]
Can you make a PR to correct the code to reflect the updated documentation?

Additionally can you expand the itest coverage to utilize this parameter so that it stays fixed in the future?
https://github.com/thefactory/marathon-python/blob/master/itests/steps/marathon_steps.py#L33
