### ISSUE TITLE
0.7.1 tag missing

### ISSUE THREAD

**Issue by bacoboy** [thefactory/marathon-python#61]
Looks like 0.7.1 didn't get tagged.
It appears to be this commit id: 13fe7c3e0f3f52af47bb1f9f1d0e3af4b5b1ca7b
Please push a tag to github and add to release page w/ correct date.
Thx

Of course a NEWER version to fix https://github.com/thefactory/marathon-python/commit/13fe7c3e0f3f52af47bb1f9f1d0e3af4b5b1ca7b#commitcomment-12627639 would also be nice :pray:

**Comment by solarkennedy** [comment]
@mbabineau I can do the tagging if you want, but can you also make a new 7.2 release and push it up?

**Comment by bacoboy** [comment]
Looks like that too has been requested here: #62 

Are the owners on vacation?  Its been a month and find myself trying to update again without a real release :(

**Comment by mbabineau** [comment]
Here we go, appreciate the patience:
https://pypi.python.org/pypi/marathon/0.7.2

@solarkennedy, do you have a PyPI account? Would love to grant you maintainer perms so I'm not the bottleneck :)

**Comment by solarkennedy** [comment]
@mbabineau totally! Share it with `solarkennedy` on pypi.

**Comment by mbabineau** [comment]
@solarkennedy https://pypi.python.org/pypi/marathon
![image](https://cloud.githubusercontent.com/assets/53127/9966319/0969d464-5df1-11e5-9128-94e3016cf263.png)

**Comment by bacoboy** [comment]
OK so no 0.7.1 tag because no 0.7.1 release ever occurred right?
