### ISSUE TITLE
When will you guys release 0.7.2

### ISSUE THREAD

**Issue by alaudatest** [thefactory/marathon-python#62]
I upgrade marathon to 0.9.1. So I need upgrade marathon-python. I saw the change log about 0.7.2.But I can't pip install it.

**Comment by bacoboy** [comment]
Yes please.  Make a release so I don't have to have a fork :(

**Comment by mbabineau** [comment]
Here you go, sorry about the delay:
https://pypi.python.org/pypi/marathon/0.7.2
