### ISSUE TITLE
Python 3 test not running

### ISSUE THREAD

**Issue by jofusa** [thefactory/marathon-python#80]
I don't think the .travis.yml is setup correctly to run python3 tests. I am hitting some python3 errors. 

py27 and py34 are declared as dependencies and travis is correctly but the tox.ini is hard coding py2.7

Here is the log from the last stable travis run:

```
source ~/virtualenv/python3.4/bin/activate
$ python --version
Python 3.4.2  <-------CORRECT
$ pip --version
pip 6.0.7 from /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages (python 3.4)
install
1.67s$ pip install tox
You are using pip version 6.0.7, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting tox
  Downloading tox-2.2.1-py2.py3-none-any.whl
Collecting pluggy<0.4.0,>=0.3.0 (from tox)
  Downloading pluggy-0.3.1-py2.py3-none-any.whl
Collecting virtualenv>=1.11.2 (from tox)
  Downloading virtualenv-13.1.2-py2.py3-none-any.whl (1.7MB)
    100% |################################| 1.7MB 172kB/s 
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.17 in /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages (from tox)
Installing collected packages: virtualenv, pluggy, tox
Successfully installed pluggy-0.3.1 tox-2.2.1 virtualenv-13.1.2
8.51s$ make test
tox
py create: /home/travis/build/thefactory/marathon-python/.tox/py
py installdeps: -rrequirements.txt, pytest, mock
py develop-inst: /home/travis/build/thefactory/marathon-python
py installed: funcsigs==0.4,-e git+https://github.com/thefactory/marathon-python.git@a246bb2473e5dd1aa7775aade59cdf96f80e1d45#egg=marathon-dev,mock==1.3.0,pbr==1.8.1,py==1.4.31,pytest==2.8.4,requests==2.8.1,requests-mock==0.7.0,six==1.10.0,wheel==0.24.0
py runtests: PYTHONHASHSEED='3066453394'
py runtests: commands[0] | py.test -s tests
============================= test session starts ==============================
platform linux2 -- Python 2.7.9, pytest-2.8.4, py-1.4.31, pluggy-0.3.1  <-------NOT CORRECT!!!!!
rootdir: /home/travis/build/thefactory/marathon-python, inifile: 
collected 3 items 
tests/test_api.py ...
```

This is the issue i think: https://github.com/thefactory/marathon-python/blob/master/tox.ini#L9

**Comment by solarkennedy** [comment]
Hmm. I had a hunch this was happening.
Even if you removed the tox line, would that be enough?

Looking at more complicated python+travis+tox setups, it looks like you have to pass in more things:
https://github.com/twisted/klein/blob/master/tox.ini
https://github.com/twisted/klein/blob/master/.travis.yml

And then *not* matrix on `python:` ?

Do you feel comfortable making a PR to fix?

**Comment by jofusa** [comment]
i will put a pr in.

**Comment by yuywz** [comment]
Hi guys, is anyone working on this issue? 
I want to use marathon-python in OpenStack [1] project, but according to the community policy, only the python 3 compatible libraries are allowed to be added to OpenStack dependency, please see the comments in this patch [2] for detail. 
Can you please help to resolve this issue? Thanks in advance!

[1]http://www.openstack.org/
[2]https://review.openstack.org/#/c/333264/

**Comment by yuywz** [comment]
Hi @jofusa , are you still planning to work on the PR you mentioned in comment?
This issue is blocking us from using marathon-python in OpenStack, please see my last comment for detail. It'd be a big help if you could help to fix it, thanks!
