### ISSUE TITLE
MarathonClient is not compatible with marathon 0.14.1-1.0.455.ubuntu1404

### ISSUE THREAD

**Issue by tekpig** [thefactory/marathon-python#81]
>>> client.list_apps()
{
    "acceptedResourceRoles": null, 
    "backoffFactor": 1.15, 
    "backoffSeconds": 1, 
    "labels": {}, 
    "cpus": 0.5, 
    "requirePorts": false, 
    "instances": 1, 
    "tasksStaged": 0, 
    "healthChecks": [], 
    "disk": 0, 
    "id": "/redis-3", 
    "maxLaunchDelaySeconds": 3600, 
    "container": {
        "docker": {
            "image": "redis:2.8.23", 
            "forcePullImage": false, 
            "network": "HOST", 
            "parameters": [
                {
                    "value": "true", 
                    "key": "oom-kill-disable"
                }
            ], 
            "privileged": false
        }, 
        "type": "DOCKER", 
        "volumes": [
            {
                "hostPath": "/var/log/redis-2", 
                "containerPath": "/var/log/mesos", 
                "mode": "RW"
            }
        ]
    }, 
    "deployments": [], 
    "version": "2015-12-10T07:21:46.529Z", 
    "env": {}, 
    "uris": [], 
    "mem": 64, 
    "args": null, 
    "tasksRunning": 1, 
    "dependencies": [], 
    "user": null, 
    "storeUrls": [], 
    "tasksUnhealthy": 0, 
    "versionInfo": {
        "lastScalingAt": "2015-12-10T07:21:46.529Z", 
        "lastConfigChangeAt": "2015-12-10T07:21:46.529Z"
    }, 
    "upgradeStrategy": {
        "maximumOverCapacity": 1, 
        "minimumHealthCapacity": 1
    }, 
    "cmd": "redis-server --port $PORT0 --dbfilename redis-2", 
    "tasksHealthy": 0, 
    "executor": "", 
    "ipAddress": null, 
    "ports": [
        10010
    ], 
    "constraints": []
}
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/zhechen/works/titan/marathon/client/client.py", line 132, in list_apps
    apps = self._parse_response(response, MarathonApp, is_list=True, resource_name='apps')
  File "/home/zhechen/works/titan/marathon/client/client.py", line 45, in _parse_response
    return [clazz.from_json(resource) for resource in target]
  File "/home/zhechen/works/titan/marathon/client/models/base.py", line 36, in from_json
    return cls(**{to_snake_case(k): v for k,v in attributes.items()})
TypeError: __init__() got an unexpected keyword argument 'ip_address'

**Comment by solarkennedy** [comment]
Fixed by #77, please follow that PR instead. (or if you feel really ambitious, rebase it and make a new PR)
