### ISSUE TITLE
Support Marathon 0.15.1

### ISSUE THREAD

**Issue by itamaro** [thefactory/marathon-python#84]
After trying the [PR for 0.14 support](https://github.com/thefactory/marathon-python/pull/77), I ran into the next API change for 0.15:

`TypeError: __init__() got an unexpected keyword argument 'fetch'`

**Comment by solarkennedy** [comment]
Hehe. Yea, it is a forever battle until we do #86.

**Comment by macmacbr** [comment]
Seeing same thing too. I think it'd be safe to ignore this field for now as it's the generated "local" version of the uris.

**Comment by solarkennedy** [comment]
See #92 for a PR for support

**Comment by nhandler** [comment]
@solarkennedy This can also likely be closed now that #95 is merged.
