### ISSUE TITLE
Task.app_id is None when using c.get_app("xxx").tasks

### ISSUE THREAD

**Issue by iven** [thefactory/marathon-python#9]
When I call with `c.list_tasks(app_id)`, there's no problem.

But when I call with `c.get_app(app_id).tasks[0].app_id`, I found it's `None`.

After digging into the code a bit, I found it's caused by the marathon API `/v2/apps/<app_id>` and `/v2/apps/<app_id>/tasks` return different task format.

Hope it could be fixed.

**Comment by solarkennedy** [comment]
@iven It has been a while. Can you confirm this is still an issue?

**Comment by iven** [comment]
@solarkennedy I'm not sure. I'm not using Marathon these days.

**Comment by solarkennedy** [comment]
Ok, I'm going to go ahead and close.
